### ISSUE TITLE
AWQ Quantitative Model Inference Problem

### ISSUE THREAD

**Issue by bg51717** [wejoncy/QLLM#118]
I have read the code from `qllm/modeling/q_layers/quant_linear_awq.py` .I found that if you want to use the awq quantitatived model to inference , you must have installed the `qllm.awq_inference_engine`. Is there a way without relying on the qllm.awq_inference_engine like the `QuantLinearGPTQ`?Thanks.

**Comment by wejoncy** [comment]
You can still run AWQ models if you don't care inference speed (say `awq_inference_engine` is not installed), QLLM will automatically convert to GPTQ-layer .
