### ISSUE TITLE
Unsupported model IR version: 10, max supported IR version: 9

### ISSUE THREAD

**Issue by FlexLaughing** [wejoncy/QLLM#126]
Hi wejoncy,
      I met an issue we transfer q4 model to onnx model base on nivida 3090 when check after merge onnx model.

decoder_merged.onnx  model properites:
ONNX v10
optimum-onnx
0
ai.onnx v16
com.microsoft v1
merged

my conda env onnx related version, I didnot see the detail version in requerement.txt.
(quan_debug) ubuntu@ubuntu-Z690-UD-AX-DDR4:~$ pip list |grep onnx
onnx                          1.16.1
onnx-graphsurgeon             0.3.12
onnxruntime                   1.17.3
onnxruntime-gpu               1.16.3
onnxsim                       0.4.8

[notice] A new release of pip is available: 21.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
(quan_debug) ubuntu@ubuntu-Z690-UD-AX-DDR4:~$

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/ubuntu/data/miniconda3/envs/quan_debug/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/ubuntu/data/miniconda3/envs/quan_debug/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /home/ubuntu/data/wangyan/test_qllm_debug/onnx3//decoder_merged.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:179 onnxruntime::Model::Model(onnx::ModelProto&&, const onnxruntime::PathString&, const onnxruntime::IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsupported model IR version: 10, max supported IR version: 9

**Comment by wejoncy** [comment]
Hi @FlexLaughing 
It's mostly you installed the latest onnx package and old version ONNXRUNTIME package.
Try to downgrade onnx may resolve it.

**Comment by FlexLaughing** [comment]
> Hi @FlexLaughing It's mostly you installed the latest onnx package and old version ONNXRUNTIME package. Try to downgrade onnx may resolve it.

Thanks for the quick feedback, is there any suggestion for onnx and onnxruntime version?

**Comment by wejoncy** [comment]
https://github.com/microsoft/onnxruntime/issues/16638

**Comment by wejoncy** [comment]
onnxruntime-gpu 1.16.3-->>>onnxruntime-gpu 1.18.0

**Comment by FlexLaughing** [comment]
Thanks, I will try to debug and record the different combination for onnx and onnxruntime version. Hope could write soon.

**Comment by FlexLaughing** [comment]
> onnxruntime-gpu 1.16.3-->>>onnxruntime-gpu 1.18.0

Hi wejoncy, I try with combination of different versions ,seems all failed after check onnx model.
Do you have a recommended version？it could export onnx model,but failed with check:
exporter.verify_correcness(model, sample_inputs, onnx_model_path, with_past)


Version 1:  fail with 
onnx                          1.15.0
onnx-graphsurgeon             0.3.12
onnxruntime                   1.17.1
onnxruntime-gpu               1.17.1
onnxsim                       0.4.8

Node (optimum::if) Op (If) [TypeInferenceError] Graph attribute inferencing failed: Type Error: Type parameter (T1) of Optype (MatMulNBits) bound to different types (tensor(float) and tensor(float16) in node (/model/layers.0/self_attn/o_proj/MatMulNBits).


Version 2: fail with 
onnx                          1.14.0
onnx-graphsurgeon             0.3.12
onnxruntime                   1.17.1
onnxruntime-gpu               1.17.1
onnxsim                       0.4.8
led:Node (optimum::if) Op (If) [TypeInferenceError] Graph attribute inferencing failed: Type Error: Type parameter (T1) of Optype (MatMulNBits) bound to different types (tensor(float) and tensor(float16) in node (/model/layers.0/self_attn/o_proj/MatMulNBits).

Version 3:fail with 
onnx                          1.16.1
onnx-graphsurgeon             0.3.12
onnxruntime                   1.18.0
onnxruntime-gpu               1.18.0
onnxsim                       0.4.8
Load model from /home/ubuntu/data/wangyan/test_qllm_debug/onnx4/decoder_merged.onnx failed:Node (optimum::if) Op (If) [TypeInferenceError] Graph attribute inferencing failed: Type Error: Type parameter (T1) of Optype (MatMulNBits) bound to different types (tensor(float) and tensor(float16) in node (/model/layers.0/self_attn/o_proj/MatMulNBits).

Version 4: fail with 
onnx 1.16.1
onnx-graphsurgeon 0.3.12
onnxruntime 1.17.3
onnxruntime-gpu 1.16.3
onnxsim 0.4.8

:IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsupported model IR version: 10, max supported IR version: 9

**Comment by FlexLaughing** [comment]
[decoder_with_past.zip](https://github.com/user-attachments/files/16061302/decoder_with_past.zip)
decoder_with_past.onnx_ext.data file is more than 1G ,over the upload limitation.

**Comment by wejoncy** [comment]
hmm,  It seems everyting is fine. what is the qllm cli command?

**Comment by FlexLaughing** [comment]
> hmm, It seems everyting is fine. what is the qllm cli command?

python -m qllm --model  /home/ubuntu/data/mjl/llm-awq-main/llama3-8b  --method=awq  --dataset=pileval --nsamples=16  --save ./Llama-3-8b_q4/ --export_onnx ./Llama-3-8b_q4_onnx/


failed when I load the model with onnxruntime,could you please try with decoder_with_past.onnx ?
    onnx_model_path = onnx_path_str+'/decoder.onnx'
    session = onnxruntime.InferenceSession(onnx_model_path, providers=['CUDAExecutionProvider'])

**Comment by wejoncy** [comment]
![image](https://github.com/wejoncy/QLLM/assets/9417365/b3fc81d8-8bd9-4cb2-bbf3-228c3338c65b)

Everyting is fine in my env
```
conda create -n py310 python=3.10
pip install torch numpy
git clone https://github.com/microsoft/onnxruntime.git && cd onnxruntime
bash build.sh --cmake_generator "Ninja" --config Release --cmake_extra_defines CMAKE_EXPORT_COMPILE_COMMANDS=ON --skip_tests  --build_wheel --use_cuda  --cudnn_home /usr/lib/x86_64-linux-gnu   --cuda_home /usr/local/cuda  --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES="80"
pip install build/Linux/Release/dist/onnxruntime_gpu-1.19.0-cp310-cp310-linux_x86_64.whl 

```

**Comment by FlexLaughing** [comment]
> ![image](https://private-user-images.githubusercontent.com/9417365/344929383-048bc1d4-f16d-406d-9159-e5d31521409a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTk0MDUsIm5iZiI6MTcxOTkxOTEwNSwicGF0aCI6Ii85NDE3MzY1LzM0NDkyOTM4My0wNDhiYzFkNC1mMTZkLTQwNmQtOTE1OS1lNWQzMTUyMTQwOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMTExODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRjOGRjNmQ2MzFkZTIyMTdlMzA3Y2U1OTUxMmUzMjNiMWQzZTc0Njg1NjUwYWU0YjRlMTk2OTg1NTU5NDE2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._TCBVKRmsAG360GkIPulhbiBHZ_Kyi-6rYShHiESIbY)
> 
> Everyting is fine in my env
> 
> ```
> conda create -n py310 python=3.10
> pip install torch numpy qllm
> git clone https://github.com/microsoft/onnxruntime.git && cd onnxruntime
> bash build.sh --cmake_generator "Ninja" --config Release --cmake_extra_defines CMAKE_EXPORT_COMPILE_COMMANDS=ON --skip_tests  --build_wheel --use_cuda  --cudnn_home /usr/lib/x86_64-linux-gnu   --cuda_home /usr/local/cuda  --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES="80"
> pip install build/Linux/Release/dist/onnxruntime_gpu-1.19.0-cp310-cp310-linux_x86_64.whl 
> ```
I try to compile onnxruntime in my RTX 3090,64G DDR,seems memory exhaust .
generating /home/ubuntu/onnxruntime/build/Linux/Release/_deps/onnx-build/onnx/onnx_operators_pb.py
[1138/1791] Building CUDA object CMakeFiles/onnxruntime_providers_cuda.dir/h...contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim192_bf16_sm80.cu.o

**Comment by FlexLaughing** [comment]
![企业微信截图_17199874298357](https://github.com/wejoncy/QLLM/assets/89910631/0036338e-e9d3-46f1-9865-6210fcabe10d)
I compile and install but still failed when create session,and i debug to _create_inference_session,if available_providers  value is correct?
ubuntu@ubuntu-Z690-UD-AX-DDR4:~/onnxruntime$ pip list |grep onnxruntime
onnxruntime-gpu               1.19.0

**Comment by FlexLaughing** [comment]
> > I compile and install but still failed when create session,and i debug to _create_inference_session,if available_providers value is correct? ubuntu@ubuntu-Z690-UD-AX-DDR4:~/onnxruntime$ pip list |grep onnxruntime onnxruntime-gpu 1.19.0
> 
> Yeah, It's correct. What's the error message during create session?

Traceback (most recent call last):
  File "debug_onnx.py", line 14, in <module>
    session = onnxruntime.InferenceSession(onnx_model_path, providers=['CUDAExecutionProvider'])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /home/ubuntu/data/wangyan/test_qllm_debug/onnx4//decoder                                      .onnx failed:Type Error: Type parameter (T1) of Optype (MatMulNBits) bound to different types (tensor(float) and tensor(float16) in node (/model/layers.0/                                      self_attn/o_proj/MatMulNBits).

**Comment by FlexLaughing** [comment]
![企业微信截图_17200577731202](https://github.com/wejoncy/QLLM/assets/89910631/20d9f5ba-a030-438c-a6bf-d6ef7537592c)

**Comment by FlexLaughing** [comment]
looks like error similar with https://github.com/microsoft/onnxruntime/issues/5581 ,the scales data type only support float?but we generate with float16 ?

**Comment by wejoncy** [comment]
No, I don't think so.
The thing is that I can 't repro it in my local environment.

**Comment by wejoncy** [comment]
Do you see any error message during export onnx model? I think qllm will check the output of ONNX model and Pytorch ones.

**Comment by FlexLaughing** [comment]
(auto_awq) ubuntu@ubuntu-Z690-UD-AX-DDR4:~$ pip list |grep onnx
onnx                          1.16.1
onnx-graphsurgeon             0.3.12
onnxruntime-gpu               1.19.0
onnxruntime-training          1.19.0+cu121
onnxsim                       0.4.8

[notice] A new release of pip is available: 21.3.1 -> 24.1.1
[notice] To update, run: pip install --upgrade pip
(auto_awq) ubuntu@ubuntu-Z690-UD-AX-DDR4:~$
[logfile_fail.log](https://github.com/user-attachments/files/16092859/logfile_fail.log)

**Comment by wejoncy** [comment]
I think I got it.
![image](https://github.com/wejoncy/QLLM/assets/9417365/8e0f653f-09e2-4718-8141-9af72c53a8dc)

MatmulNbits requires input_x and scales has the same dtype which is constrained by `T1`, However, the attention output is float32, which is incompatible with matmulBbits's scale

What's your transformer's version?

**Comment by FlexLaughing** [comment]
> I think I got it. ![image](https://private-user-images.githubusercontent.com/9417365/345701351-8e0f653f-09e2-4718-8141-9af72c53a8dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjk4NDMsIm5iZiI6MTcyMDA2OTU0MywicGF0aCI6Ii85NDE3MzY1LzM0NTcwMTM1MS04ZTBmNjUzZi0wOWUyLTQ3MTgtODE0MS05YWY3MmM1M2E4ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMDUwNTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmMxYjQ1NGE3MTUyMmY4ODljMTc4Y2ZiMDcyM2E3M2ZjN2U4MDA3MjFiMjQwYzU0YjhmNDI3MTc4ZWRhMGY1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KbuUXq5odyfaT0mxez87yWb1iaOFMNuOiLTgS2848W8)
> 
> MatmulNbits requires input_x and scales has the same dtype which is constrained by `T1`, However, the attention output is float32, which is incompatible with matmulBbits's scale
> 
> What's your transformer's version?

(auto_awq) ubuntu@ubuntu-Z690-UD-AX-DDR4:~$ pip list |grep tran
pytorch-transformers          1.0.0
s3transfer                    0.6.0
sentence-transformers         2.2.2
transformers                  4.41.2
transformers-stream-generator 0.0.4

**Comment by wejoncy** [comment]
It's a bug of pytorch-2.1 or below. Does your PyTorch is up-to-date?

**Comment by FlexLaughing** [comment]
> It's a bug of pytorch-2.1 or below. Does your PyTorch is up-to-date? SPDA-attention used float32 as the output-dtype , If you don't want to update PyTorch, you can set attention_impl tp "eager".

emm,got it! I update pytorch version to 2.3, and saw an env issue, I am working on it right now.
"from torch._C import *  # noqa: F403
ImportError: libcupti.so.12: cannot open shared object file: No such file or directory"

**Comment by wejoncy** [comment]
This should seems to be issues of your cuda environment.
Anyway, Force transformer to use "eager" will work for you.
https://github.com/huggingface/transformers/blob/048f599f3506e57e0a595b455d9d2834c8d45023/src/transformers/models/llama/modeling_llama.py#L666

**Comment by FlexLaughing** [comment]
> This seems to be an issue of your cuda environment. Anyway, to force transformer to use "eager" attention will work for you. https://github.com/huggingface/transformers/blob/048f599f3506e57e0a595b455d9d2834c8d45023/src/transformers/models/llama/modeling_llama.py#L666

Seems my env have some other errors, is it possible to load the onnx model base on CPU ? 
![企业微信截图_17200905188992](https://github.com/wejoncy/QLLM/assets/89910631/31d538ed-10d6-4c63-99cd-01f6f6109906)

**Comment by wejoncy** [comment]
Yes,  you can use it in CPU backend as long as you export model to onnx with dtype as float32

**Comment by FlexLaughing** [comment]
> Yes, you can use CPU EP as long as onnx model is exported with dtype as float32

Thanks, create InferenceSession works for my env with below config.

torch              2.2.2
torchaudio         2.2.2
torchvision        0.17.2
onnx               1.16.1
onnx               1.16.1
onnxruntime        1.18.1
