### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement XbitOps (from versions: none)

### ISSUE THREAD

**Issue by l793330708** [wejoncy/QLLM#22]
I met this problem when  I ran this code below. How to solve it?
`
pip install git+https://github.com/wejoncy/QLLM.git
`

**Comment by wejoncy** [comment]
Hi, Thanks for your reporting.

Could you work around it by `pip install git+https://github.com/wejoncy/QLLM.git@custom` ?

Will fix it in few days.
