### ISSUE TITLE
GPTQ QLLM

### ISSUE THREAD

**Issue by CWG-filip** [wejoncy/QLLM#35]
Something is off with this QLLM gptq quantization @wejoncy ... all the dependencies aren't specified in requirements file. Also, 3 times tried quantizing and every time it breaks when it tries to save the file or quant is done. Tried Llama2-70b and mistral 7b

<img width="761" alt="Screenshot 2023-12-09 at 15 21 57" src="https://github.com/wejoncy/QLLM/assets/72705346/e6133ebf-a8d7-400a-b321-c9c52109ab22">

**Comment by wejoncy** [comment]
Hi, thanks for trying this tool.

The issue was fixed by latest PR. Will add a UT to ensure everything is fine.
